### ISSUE TITLE
无法正常显示页面的问题

### ISSUE THREAD

**Issue by larrykoo711** [Clouda-team/Cloudajs#23]
我直接将init的程序包上传到BAE，还是无法正常访问页面，看日志有这样一个错误，我按照教程填写了mongodb的name的
访问页面也提示：

``` java
Application Cache Error event: Resource fetch failed (404) http://goodaward.duapp.com/bin/view/itworks.html 
```

这个是什么情况，我确定我的sumeru是最新的 0.7.14

``` java
FATAL:2013-07-17 11:27:38goodaward.duapp.com
--Error: database name cannot be the empty string
at validateDatabaseName (instance1/nodejs/goodaward.sx.duapp.com/app/node_modules/mongodb/lib/mongodb/db.js:195:39)
at new Db (instance1/nodejs/goodaward.sx.duapp.com/app/node_modules/mongodb/lib/mongodb/db.js:84:3)
at runnable (instance1/nodejs/goodaward.sx.duapp.com/app/sumeru/server/DbCollectionHandler.js:141:18)
at Object.<anonymous> (instance1/nodejs/goodaward.sx.duapp.com/app/sumeru/server/run.js:70:73)
at Module.wrappedCompile [as _compile] (instance1/nodejs/runtime/src/sandbox/modules/module.js:118:25)
at Object.Module._extensions..js (module.js:502:10)
at Module.load (module.js:392:32)
at Function.Module._load (module.js:350:12)
at Module.require (module.js:398:17)
at require (instance1/nodejs/runtime/src/sandbox/modules/module.js:42:15)
```

**Comment by shanewei** [comment]
第一个404 影响不是很大吧 你可以把view下的itwork.html 复制到/bin/view下试试。

不过init程序在view下应该是有这个文件的呀。

**Comment by larrykoo711** [comment]
的确/bin/view 下面是有的，无法找到原因了。

**Comment by ganxun1** [comment]
根据log的信息看出是在BAE上数据库的名称没有配置导致后台错误，可按以下方法解决：

在sumeru/src/frameworkConfig.js中找到（第10行左右）
// BAE CONFIG  
    if (typeof process !== 'undefined' && typeof process.BAE !== 'undefined'){
        dbname = "";
        socketPort = process.env.APP_PORT;
        httpServerPort = 0;
        whiteList = ['xhr-streaming'];
    }
将BAE上获取的数据库名填入 dbname = ""; 中

**Comment by larrykoo711** [comment]
这一步可以确认，绝对是填了的

**Comment by larrykoo711** [comment]
问题已经解决，看错了mongodb的dbname的位置，是第12行，大家注意下
