### ISSUE TITLE
sumeru start失败

### ISSUE THREAD

**Issue by kevinunic** [Clouda-team/Cloudajs#6]
你好，在ubuntu下，按照教程创建项目后，运行sumeru start出现一下错误：
NON BAE MODE

BaseDir :/home/kevin/sumeru/myproject/
DstDir :/home/kevin/sumeru/myproject/app

/home/kevin/sumeru/myproject/sumeru/build/buildJavascript.js:73

```
var ast = UglifyJS.parse(orig_code); // parse code and get the initial AST

           ^
```

TypeError: Object function uglify(orig_code, options){
  options || (options = {});
  var jsp = uglify.parser;
  var pro = uglify.uglify;

  var ast = jsp.parse(orig_code, options.strict_semicolons); // parse code and get the initial AST
  ast = pro.ast_mangle(ast, options.mangle_options); // get a new AST with mangled names
  ast = pro.ast_squeeze(ast, options.squeeze_options); // get an AST with compression optimizations
  var final_code = pro.gen_code(ast, options.gen_options); // compressed code here
  return final_code;
} has no method 'parse'
    at module.exports (/home/kevin/sumeru/myproject/sumeru/build/buildJavascript.js:73:24)
    at Object.<anonymous> (/home/kevin/sumeru/myproject/sumeru/build/build.js:45:51)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/kevin/sumeru/myproject/sumeru/server/run.js:1:63)
    at Module._compile (module.js:456:26)

**Comment by tongyao** [comment]
请npm update -g sumeru升级到最新版本后重新sumeru init再试试

**Comment by kevinunic** [comment]
Thanks, 问题已解决！！！
